server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.74.130
    username: leyou
    password: leyou
    virtual-host: /leyou
leyou:
  sms:
    accessKeyId: LTAI4FgX2b25D8hL6EVy1Nsx # 你自己的accessKeyId
    accessKeySecret: HLlrmd2zy9BD7Wud193NxwyRGGFnNo # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_175537376 # 模板名称