server:
  port: 8083
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
spring:
  rabbitmq:
    host: 192.168.74.130
    username: leyou
    password: leyou
    virtual-host: /leyou
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
  application:
    name: search-service
  datasource:
    url: jdbc:mysql://localhost:3306/heima?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.74.130:9300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
